openapi: 3.0.1
info:
  title: Worst Movie API
  version: 1.0.0
paths:
  /producers:
    get:
      tags:
        - Producer
      summary: Get the producer with the longest gap between two consecutive awards
      operationId: getIntervals
      responses:
        '200':
          description: Get the producer with the longest gap between two consecutive awards
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AwardInterval'
                example:
                  min:
                    - producer: "Producer 1"
                      interval: 1
                      previousWin: 2008
                      followingWin: 2009
                    - producer: "Producer 2"
                      interval: 1
                      previousWin: 2018
                      followingWin: 2019
                  max:
                    - producer: "Producer 1"
                      interval: 99
                      previousWin: 1900
                      followingWin: 1999
                    - producer: "Producer 2"
                      interval: 99
                      previousWin: 2000
                      followingWin: 2099
components:
  schemas:
    AwardInterval:
      type: object
      properties:
        min:
          type: array
          items:
            $ref: '#/components/schemas/ProducerInterval'
        max:
          type: array
          items:
            $ref: '#/components/schemas/ProducerInterval'
    ProducerInterval:
      type: object
      properties:
        producer:
          type: string
          example: "Producer 1"
        interval:
          type: integer
          example: 1
        previousWin:
          type: integer
          format: int32
          example: 2008
        followingWin:
          type: integer
          format: int32
          example: 2009
